package com.wuchenyv1990.mybatis.generator.mapper;

import com.wuchenyv1990.mybatis.generator.model.Group;
import java.util.List;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int deleteByPrimaryKey(Long gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    Group selectByPrimaryKey(Long gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    List<Group> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int updateByPrimaryKey(Group record);
}