package com.wuchenyv1990.mybatis.generator.mapper;

import com.wuchenyv1990.mybatis.generator.model.UserToGroup;
import java.util.List;

public interface UserToGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int insert(UserToGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    UserToGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    List<UserToGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_to_group
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    int updateByPrimaryKey(UserToGroup record);
}