package com.wuchenyv1990.mybatis.generator.model;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.gid
     *
     * @return the value of group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.gid
     *
     * @param gid the value for group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}