package com.wuchenyv1990.mybatis.generator.model;

public class UserToGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_to_group.id
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_to_group.uid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_to_group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_to_group.id
     *
     * @return the value of user_to_group.id
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_to_group.id
     *
     * @param id the value for user_to_group.id
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_to_group.uid
     *
     * @return the value of user_to_group.uid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_to_group.uid
     *
     * @param uid the value for user_to_group.uid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_to_group.gid
     *
     * @return the value of user_to_group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_to_group.gid
     *
     * @param gid the value for user_to_group.gid
     *
     * @mbg.generated Fri Jun 05 16:38:49 CST 2020
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}