spring:
  application:
    name: app-clients

server:
  port: 8765
  eureka: 8761

#打开feign的hystrix支持
feign:
  hystrix:
    enabled: true

#超时时间，否则由于懒加载第一次调用会失败 test1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka}/eureka/

