spring:
  application:
    name: app-clients

server:
  port: 8765
  eureka: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka}/eureka/
