spring:
  profiles:
    active: b
  application:
    name: eureka-client

server:
  eureka: 8761
  port: 8764

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka}/eureka/

---
spring:
  profiles: a
server:
  port: 8762
---
spring:
  profiles: b
server:
  port: 8763
