spring:
  application:
    name: sleuth-app
  sleuth:
    web:
      client:
        enabled: true
    # 采样率
    sampler:
      probability: 1.0
  # zipkin地址 默认值就是
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8766
  eureka: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.eureka}/eureka/
